name: sangria
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./volumes/mongo/db:/data/db
      - ./volumes/mongo/configdb:/data/configdb
    ports:
      - 27017:27017
    networks:
      - dev
    command: --quiet --logpath /dev/null 
  server:
    depends_on:
      - mongo
    build: ./server
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - dev
    environment:
      - MONGO_URI=mongodb://mongo:27017/sangria
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: ./app
          ignore:
            - node_modules/
            - uploads/
  assets:
    build: ./assets
    volumes:
      - ./server/assets:/app/dist
    develop:
      watch:
        - action: sync+restart
          path: ./assets
          target: ./app
          ignore:
            - node_modules/
networks:
  dev:
    driver: bridge