name: burgundy
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./volumes/mongo/db:/data/db
      - ./volumes/mongo/configdb:/data/configdb
    ports:
      - 27017:27017
    networks:
      - dev
  server:
    depends_on:
      - mongo
    build: ./server
    volumes:
      - ./server/uploads:/app/server/uploads
    ports:
      - 3000:3000
    networks:
      - dev
    environment:
      - MONGO_URI=mongodb://mongo:27017/burgundy
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: ./app/server
          ignore:
            - node_modules/
            - uploads/
networks:
  dev:
    driver: bridge