name: burgundy
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./volumes/mongo/db:/data/db
      - ./volumes/mongo/configdb:/data/configdb
    networks:
      - dev
  app:
    build: .
    ports:
      - 3000:3000
    networks:
      - dev
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: ./app/server
          ignore:
            - node_modules/
        - action: rebuild
          path: ./assets/src
          target: ./app/assets/src
networks:
  dev:
    driver: bridge