name: burgundy
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./volumes/mongo/db:/data/db
      - ./volumes/mongo/configdb:/data/configdb
    networks:
      - dev
  assets:
    build: ./assets
    ports:
      - 80:80
    volumes:
      - ./assets/dist:/app/dist
    develop:
      watch:
        - action: rebuild
          path: ./assets/src
          target: ./app/src
        - action: rebuild
          path: ./assets/package.json
          target: ./app/package.json
  server:
    depends_on:
      - mongo
    build: ./server
    ports:
      - 3000:3000
    networks:
      - dev
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: ./app/server
          ignore:
            - node_modules/
        - action: rebuild
          path: ./assets/src
          target: ./app/assets/src
networks:
  dev:
    driver: bridge